### PR TITLE
Post: Maltego Transforms for the Lazy

### PR DESCRIPTION
**Pull request by sroberts**
I’ve written a lot of Maltego transforms lately. I think that’d be useful to share.

### CODE REVIEW

**Comment by krmaxwell** [comment]
If possible (it may not be for you), stuff about transform servers (e.g. TDS) would be good, too.

Let me know if I can help in any way.

**Comment by sroberts** [comment]
Yeah I don't have a TDS, don't know a lot about them, and I admit I'm reluctant to run things through someone else's server. I'm also intending this post to be a very "quick and dirty" approach to getting transforms going. I had a a hard time piecing together all the information, but once I didI was suddenly able to generate transforms quickly, though not pretty, and I'd like to impart some of what I missed in that regard.

**Comment by krmaxwell** [comment]
> I had a a hard time piecing together all the information, but once I didI was suddenly able to generate transforms quickly, though not pretty, and I'd like to impart some of what I missed in that regard.

image

(though maybe I'll write a follow-on post on my site explaining the differences between the various types of remote options)

**Comment by sroberts** [comment]
I think that'd be super valuable. I would happily include it, but I just don't know them well.

**Comment by sroberts** [comment]
If you want to check this post out (and I'd welcome feedback) you'll need to download the whole thing and run ```jekyll serve``` to show a lot of the dynamic embeds.

**Comment by krmaxwell** [comment]
what did you use to generate that GIF?

**Comment by sroberts** [comment]
All that work and that's your biggest question?!

QuickTime for capture to MP4 then GifBrewery to convert it to a gif. I'm not thrilled with it but after playing for an hour it's the best I could do.

**Comment by krmaxwell** [comment]
no it was the most coherent question I could ask pre-:coffee:

**Comment by sroberts** [comment]
image

**Pull request merged**
