### PR TITLE
Hunting Tools

### PR DESCRIPTION
**Pull request by sroberts**
A follow up to my post on building a Hunt team, reviewing open source tools that could get a team started.

### CODE REVIEW

**Comment by krmaxwell** [comment]
- You mention MIG but don't give it any context. Might be worth saying a few things about it
- No :heart: for MISP or MozDef?

**Comment by sroberts** [comment]
I should at least add a link to MIG. You're right.

I don't look at a SIEM as a "hunting tool", to me that's more a traditional IR system. 

MISP I don't know, never actually set it up.

**Comment by krmaxwell** [comment]
Dunno enough about MozDef. Thought it was supposed to be "not just a SIEM" but I could be wrong.

**Comment by sroberts** [comment]
Nothing admits to being "just a ______". I have no doubt it's a great tool, and I certainly would look at deploying it. But I don't think it would insanely level up the hunting potential of a team the way other tools might.

**Comment by sroberts** [comment]
But otherwise the post looks ok?

**Comment by krmaxwell** [comment]
Well I haven't touched the editing bit. I tried really hard to look at content over presentation this time ;)

**Comment by sroberts** [comment]
Wow.... I think you're growing...

**Pull request merged**
