### PR TITLE
Post: Home Office Setup

### PR DESCRIPTION
**Pull request by sroberts**
- [ ] Passes CI
- [ ] Spell Checked
- [ ] Peer Reviewed
- [ ] Dated Correctly

I had a random idea of doing a semi-annotated picture of my home office setup. I wasn't crazy about the way I laid it out, and then i started questioning if anyone would even care to read it. Maybe I need a second opinion.

### CODE REVIEW

**Comment by sroberts** [comment]
@krmaxwell Is this actually worth writing?

**Comment by krmaxwell** [comment]
People eat this stuff up. Add a bit more narrative about what drives your choices and things you might experiment with (or already have) and you're golden.

**Comment by deadbits** [comment]
I'd read it. I find different personal home office setups interesting. Gives me ideas for ways to better improve my own, plus every good hacker loves some desk & monitor porn ;-)

**Comment by sroberts** [comment]
@deadbits Good to know. I'll try to get it out this week.

**Comment by krmaxwell** [comment]
some additional things to think about: http://www.hackersusethis.com/p/the-questions.html

**Comment by sroberts** [comment]
- https://www.producthunt.com/e/2015-trends-remote-work
- https://twitter.com/cobyism/status/691619389842571265

**Pull request closed without merging**
